import Airtable from "airtable";

export const base = new Airtable({
  apiKey: import.meta.env.VITE_AIRTABLE_API_KEY,
}).base(import.meta.env.VITE_AIRTABLE_BASE_ID);

export const states = [
  { name: "Abia", value: "Abia" },
  { name: "Adamawa", value: "Adamawa" },
  { name: "Akwa Ibom", value: "Akwa Ibom" },
  { name: "Anambra", value: "Anambra" },
  { name: "Bauchi", value: "Bauchi" },
  { name: "Bayelsa", value: "Bayelsa" },
  { name: "Benue", value: "Benue" },
  { name: "Borno", value: "Borno" },
  { name: "Cross River", value: "Cross River" },
  { name: "Delta", value: "Delta" },
  { name: "Ebonyi", value: "Ebonyi" },
  { name: "Edo", value: "Edo" },
  { name: "Ekiti", value: "Ekiti" },
  { name: "Enugu", value: "Enugu" },
  { name: "Gombe", value: "Gombe" },
  { name: "Imo", value: "Imo" },
  { name: "Jigawa", value: "Jigawa" },
  { name: "Kaduna", value: "Kaduna" },
  { name: "Kano", value: "Kano" },
  { name: "Katsina", value: "Katsina" },
  { name: "Kebbi", value: "Kebbi" },
  { name: "Kogi", value: "Kogi" },
  { name: "Kwara", value: "Kwara" },
  { name: "Lagos", value: "Lagos" },
  { name: "Nasarawa", value: "Nasarawa" },
  { name: "Niger", value: "Niger" },
  { name: "Ogun", value: "Ogun" },
  { name: "Ondo", value: "Ondo" },
  { name: "Osun", value: "Osun" },
  { name: "Oyo", value: "Oyo" },
  { name: "Plateau", value: "Plateau" },
  { name: "Rivers", value: "Rivers" },
  { name: "Sokoto", value: "Sokoto" },
  { name: "Taraba", value: "Taraba" },
  { name: "Yobe", value: "Yobe" },
  { name: "Zamfara", value: "Zamfara" },
];

export const units = [
  { name: "Administrative", value: "Administrative" },
  { name: "Executive", value: "Executive" },
  { name: "Technical", value: "Technical" },
  { name: "Clerical", value: "Clerical" },
  { name: "Secretaries", value: "Secretaries" },
  { name: "Computer Operators", value: "Computer Operators" },
  { name: "Estate Officer", value: "Estate Officer" },
  { name: "Works", value: "Works" },
  { name: "Securities", value: "Securities" },
  { name: "Town Planners", value: "Town Planners" },
  { name: "Accountants", value: "Accountants" },
  { name: "Doctors", value: "Doctors" },
  { name: "Nurses", value: "Nurses" },
  { name: "System Analyst", value: "System Analyst" },
  { name: "Pharmacists", value: "Pharmacists" },
  { name: "Library Officers", value: "Library Officers" },
  { name: "Legal Officers", value: "Legal Officers" },
  { name: "Architect", value: "Architect" },
  { name: "Engineers", value: "Engineers" },
  { name: "Farm Officers", value: "Farm Officers" },
];

export const nonAcademic = [
  { name: "Deputy Bursars", value: "Deputy Bursars" },
  { name: "Doctors", value: "Doctors" },
  { name: "Matrons", value: "Matrons" },
  {
    name: "Principal Assistant Registrars",
    value: "Principal Assistant Registrars",
  },
  { name: "Senior Assistant Registrars", value: "Senior Assistant Registrars" },
  { name: "Pharmacists", value: "Pharmacists" },
  { name: "Secretaries", value: "Secretaries" },
  { name: "System Analyst", value: "System Analyst" },
  { name: "Accountants", value: "Accountants" },
  { name: "Assistant Registrars", value: "Assistant Registrars" },
  { name: "Works (Senior)", value: "Works (Senior)" },
  { name: "Admin Officers", value: "Admin Officers" },
  { name: "Admin Assistants", value: "Admin Assistants" },
  { name: "Legal Officers", value: "Legal Officers" },
  { name: "Computer Operators", value: "Computer Operators" },
  { name: "Nurses", value: "Nurses" },
  { name: "Library Officers", value: "Library Officers" },
  { name: "Security (Senior)", value: "Security (Senior)" },
  { name: "Farm Officers", value: "Farm Officers" },
  { name: "Executive Officers", value: "Executive Officers" },
  { name: "Architects", value: "Architects" },
  { name: "Engineers", value: "Engineers" },
  { name: "Estate Officers", value: "Estate Officers" },
  { name: "Town Planners", value: "Town Planners" },
  { name: "Technologists", value: "Technologists" },
  { name: "Junior Staff", value: "Junior Staff" },
  { name: "Contract Staff", value: "Contract Staff" },
  { name: "Internship", value: "Internship" },
];

export const academic = [
  { name: "Professor", value: "Professor" },
  { name: "Reader", value: "Reader" },
  { name: "Senior Lecturer", value: "Senior Lecturer" },
  { name: "Lecturer I", value: "Lecturer I" },
  { name: "Lecturer II", value: "Lecturer II" },
  { name: "Assistant Lecturer", value: "Assistant Lecturer" },
  { name: "Graduate Assistant", value: "Graduate Assistant" },
  { name: "Clinical Instructor", value: "Clinical Instructor" },
];

export const levels = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
];

export const employmentTypes = [
  { name: 'Permanent', value: 'Permanent' },
  { name: 'Contract', value: 'Contract' },
  { name: 'Adjunct', value: 'Adjunct' },
  { name: 'Sabbatical', value: 'Sabbatical' }
];